sudo: false
language: ruby
cache: bundler
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/shards.yml.example config/shards.yml
  - cp config/faye.yml.example config/faye.yml
  - cp dotenv.example .env
  - mysql -e 'create database test_sparc_request;'
  - mysql -e 'create database cwf_test;'  
  - cd ..
  - git clone https://github.com/sparc-request/sparc-request.git
  - cd sparc-request
  - rvm use $(< .ruby-version) --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ..
  - pwd
  - rvm use $(< .ruby-version) --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
script:
  - RAILS_ENV=test bundle exec rake db:migrate 
  - bundle exec rspec  
